/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TDn9.Proprietes;
import TDn9.Paires.IPaire;
import TDn9.Paires.Paire; 

public class App {
    public static void exo2q2() {
        IPaire<Integer, String> p1 = new Paire<>(1, "un");
        System.out.println(p1);
        IPaire<Double, String> p2 = p1.changeFst(1.0);
        System.out.println(p2);
        IPaire<Double, IPaire<Integer, String>> p3 = p2.changeSnd(p1);
        System.out.println(p3);
    }
}
